# frontend/Dockerfile.prod

# Etapa 1: build de Vite
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Usa el .env.production de Vite
RUN npm run build

# Etapa 2: servir estáticos con Nginx
FROM nginx:alpine

# Copiamos el build al HTML de nginx
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
